### PR TITLE
Remove 'register' keyword which was removed in C++17

### LINKED ISSUE #14: Does not compile with C++ 17 compiler
The code does not compile with a compiler in C++ 17 mode, such as gcc/cpp 11.3.

```
lib/assembler_0.h:94:40: error: ISO C++17 does not allow ‘register’ storage class specifier [-Werror=register]
   94 |   void cover_row(register unsigned int r);
      |                                        ^
```

The `register` keyword was deprecated and finally removed in C++ 17.

### PR DESCRIPTION
**Pull request by raoulb**
Fixes #14

### CODE REVIEW

**Review by TheRammer — APPROVED** [review]
I independently resolved these same warnings ("ISO C++17 does not allow ‘register’ storage class specifier [-Wregister]") and resulted in the same diffs.

**Comment by raoulb** [comment]
Someone with the suitable privileges should merge it.

**Comment by akoehn** [comment]
My pleasure.  Somehow lost this PR in my ~16k unread emails :-/

**Comment by raoulb** [comment]
Thanks :)

**Pull request merged**
